<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAF3IULC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAF3IULC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAF3IULC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAF3IULC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAF3IULC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AF3IULC',
    'container.build_id' => 'b9f6d40a',
    'container.build_time' => 1619359471,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAF3IULC');
