<?php


namespace App\Repository;

use App\Entity\Factor;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
class CinemaRepository extends ServiceEntityRepository{
    public function rate($rate)
        $query->this->public function createQueryBuilder($alias, $indexBy = null)
{
    return parent::createQueryBuilder($alias, $indexBy); // TODO: Change the autogenerated stub
}
}
