<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWvpeha\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWvpeha/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPWvpeha.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPWvpeha\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPWvpeha\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PWvpeha',
    'container.build_id' => 'eb4a9758',
    'container.build_time' => 1619224702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWvpeha');
