<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Film extends \App\Entity\Film implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'trailer', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'rdate', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'director', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'imageb'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'trailer', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'genre', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'rdate', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'image', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'director', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Film' . "\0" . 'imageb'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Film $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrailer(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrailer', []);

        return parent::getTrailer();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrailer(string $trailer): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrailer', [$trailer]);

        return parent::setTrailer($trailer);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre(string $genre): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getRdate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRdate', []);

        return parent::getRdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRdate(\DateTimeInterface $rdate): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRdate', [$rdate]);

        return parent::setRdate($rdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirector(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirector', []);

        return parent::getDirector();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirector(string $director): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirector', [$director]);

        return parent::setDirector($director);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageb(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageb', []);

        return parent::getImageb();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageb(string $imageb): \App\Entity\Film
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageb', [$imageb]);

        return parent::setImageb($imageb);
    }

}
